/* AVERAGE SALARY*/

SELECT ROUND(AVG(REGULAR_PAY), 2) AS Average_salary
FROM Pay
;    


/* LOWEST-PAID EMPLOYEE*/

SELECT Pay.EMPLOYEE_NO, Pay.REGULAR_PAY
FROM Pay
WHERE Pay.REGULAR_PAY = (SELECT MIN(REGULAR_PAY) FROM PAY)
;

/* HIGHEST-PAID EMPLOYEE*/

SELECT Pay.EMPLOYEE_NO, Pay.REGULAR_PAY
FROM Pay
WHERE Pay.REGULAR_PAY = (SELECT MAX(REGULAR_PAY) FROM PAY)
;

/* SALARY DISTRIBUTION ACROSS DEPARTMENTS*/

SELECT Department.DEPARTMENT_TITLE, ROUND(AVG(REGULAR_PAY), 2) AS Salary_average
FROM Department
JOIN Employee ON Department.DEPARTMENT_NO = Employee.DEPARTMENT_NO
JOIN Pay ON Employee.EMPLOYEE_NO = Pay.EMPLOYEE_NO
GROUP BY DEPARTMENT_TITLE
ORDER BY AVG(REGULAR_PAY) DESC
;

/* SALARY DISTRIBUTION ACROSS JOBS*/

SELECT Job.JOB_TITLE, ROUND(AVG(REGULAR_PAY), 2) AS Salary_average
FROM Job
JOIN Employee ON Job.JOB_CLASS_PGRADE = Employee.JOB_CLASS_PGRADE
JOIN Pay ON Employee.EMPLOYEE_NO = Pay.EMPLOYEE_NO
GROUP BY JOB_TITLE
ORDER BY AVG(REGULAR_PAY) DESC
;

/* DISTRIBUTION OF EMPLOYEES BY ETHNICITY */

SELECT ETHNICITY, COUNT(Employee.EMPLOYEE_NO) AS Number_of_Employees
FROM Employee
GROUP BY ETHNICITY
ORDER BY COUNT(Employee.EMPLOYEE_NO) DESC
;


/*DEPARTMENTS WITH THE HIGHEST DIVERSITY*/

SELECT Department.DEPARTMENT_TITLE, COUNT(DISTINCT Employee.ETHNICITY) AS Ethnicities
FROM Department
JOIN Employee ON Department.DEPARTMENT_NO = Employee.DEPARTMENT_NO
GROUP BY Department.DEPARTMENT_TITLE
HAVING Ethnicities >= 5
ORDER BY Ethnicities DESC
LIMIT 10
;


/* EMPLOYEES WITH THE HIGHEST AMOUNT OF OVERTIME*/

SELECT EMPLOYEE_NO, OVERTIME_PAY
FROM Pay
ORDER BY OVERTIME_PAY DESC
LIMIT 10
;

/* AVERAGE OVERTIME PAY BY DEPARTMENT */

SELECT DEPARTMENT_TITLE, ROUND(AVG(OVERTIME_PAY), 2) AS Overtime_pay
FROM Department
JOIN Employee ON Department.DEPARTMENT_NO = Employee.DEPARTMENT_NO
JOIN Pay ON Employee.EMPLOYEE_NO = Pay.EMPLOYEE_NO
GROUP BY DEPARTMENT_TITLE
ORDER BY AVG(OVERTIME_PAY) DESC
;


/* TOTAL EMPLOYEES BY DEPARTMENT */

SELECT DEPARTMENT_TITLE, COUNT(EMPLOYEE_NO) AS Total_Employees
FROM Department
JOIN Employee ON Department.DEPARTMENT_NO = Employee.DEPARTMENT_NO
GROUP BY DEPARTMENT_TITLE
ORDER BY COUNT(EMPLOYEE_NO) DESC
;


/* BENEFITS BY DEPARTMENT */

SELECT DEPARTMENT_TITLE, ROUND(SUM(CITY_RETIREMENT_CONTRIBUTIONS) + SUM(BENEFIT_PAY), 2) AS Total_Benefits
FROM Department
JOIN Employee ON Department.DEPARTMENT_NO = Employee.DEPARTMENT_NO
JOIN Benefits ON Employee.EMPLOYEE_NO = Benefits.EMPLOYEE_NO
GROUP BY DEPARTMENT_TITLE
ORDER BY Total_Benefits DESC
;

/* DEPARTMENTS WITH HIGHEST COST BY EMPLOYEES */


SELECT DEPARTMENT_TITLE, ROUND(AVG(TOTAL_PAY) + AVG(CITY_RETIREMENT_CONTRIBUTIONS) + AVG(BENEFIT_PAY), 2) AS Total_Cost
FROM Department
JOIN Employee ON Department.DEPARTMENT_NO = Employee.DEPARTMENT_NO
JOIN Pay ON Employee.EMPLOYEE_NO = Pay.EMPLOYEE_NO
JOIN Benefits ON Pay.EMPLOYEE_NO = Benefits.EMPLOYEE_NO
GROUP BY DEPARTMENT_TITLE
ORDER BY Total_Cost DESC
LIMIT 10
;


